stages:
  - test
  - release

release:
  image: docker-registry.widas.de:5050/dockerregistry/common/semantic-release:v1.0.4
  stage: release
  script:
    - npm install -g typescript
    - npm ci --production
    - npm run build
    - npm config set always-auth true
    - npm config set @cidaas-public-devkits:registry=https://gitlab.widas.de/api/v4/projects/${CI_PROJECT_ID}/packages/npm/
    - npm config set -- //gitlab.widas.de/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${GITLAB_TOKEN}
    - git tag -d $(git tag -l)
    - git fetch --all --tags
    - semantic-release
  only:
    - development

code_quality_json:
  image: docker:git
  stage: test
  allow_failure: true
  variables:
    CODE_QUALITY_IMAGE: "codeclimate/codeclimate:latest"
  script:
    - docker pull "$CODE_QUALITY_IMAGE"
    - docker run
       --env SOURCE_CODE="$PWD"
       --env CODECLIMATE_CODE="$PWD"
       --volume "$PWD":/code
       --volume /var/run/docker.sock:/var/run/docker.sock
       --volume /tmp/cc:/tmp/cc
       "$CODE_QUALITY_IMAGE" analyze -f json > gl-code-quality-report.json
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
    paths: [gl-code-quality-report.json]
  dependencies: []
