stages:
  - release

release:
  image: docker-registry.widas.de:5050/dockerregistry/common/semantic-release:v1.0.4
  stage: release
  script:
    - npm install -g typescript
    - npm ci --production
    - npm run build
    - npm config set always-auth true
    - npm config set @cidaas:registry=https://gitlab.widas.de/api/v4/projects/${CI_PROJECT_ID}/packages/npm/
    - npm config set -- //gitlab.widas.de/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${GITLAB_TOKEN}
    - git tag -d $(git tag -l)
    - git fetch --all --tags
    - semantic-release
  only:
    - main
