stages:
    - release

variables:
    DOCKER_DRIVER: overlay2
    SCRIPTS_PATH: cidaas-versioning-ci-templates/scripts/js-sdk

release:
    stage: release
    image: node:14
    before_script:
        - mkdir -p ~/.docker
        - echo $CIM_DOCKER_REG_NEXUS > ~/.docker/config.json
    script:
        - apt update && apt install jq -y
        - npm install -g npm-cli-adduser
        - npm install --save-dev semantic-release
        - chmod 700 ./${SCRIPTS_PATH}/init_npmrc.sh
        - ./${SCRIPTS_PATH}/init_npmrc.sh
        - npm install typescript -g
        - npm run build
        - rm -rf ./lib ./scripts ./spec .gitlab-ci.yml ./cidaas-versioning-ci-templates
        - npm-cli-adduser --registry=http://nexus.widas.de/repository/npm-internal/ --username $NPM_USERNAME --password $NPM_PASSWORD --email $NPM_EMAIL
        - npm run semantic-release
        - echo "PACKAGE_VERSION="$(cat package.json | jq .version)"" >> variables.env
    artifacts:
      reports:
        dotenv:
          - variables.env
    only:
        -  main
